apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q7m5uc16k-nodejs 
  janus-idp.io/tekton: q7m5uc16k-nodejs
  backstage.io/kubernetes-id: q7m5uc16k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q7m5uc16k-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml